### ISSUE TITLE
Read open weather map Documentation

### ISSUE THREAD

**Issue by FOR-TIMI** [sahebbhalla/BERG#3]
Hey, Can you please read the open weather map documentation and figure out how we can get the current weather of a city?

**Comment by threewide** [comment]
When I was looking at the api to make sure i got the key right it gave an example call of london, uk using the API:
http://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=d582054f0f0dcf06c41ec1c6aa2bd8a9
I changed the uk in the link to ca to get London Canada's current weather:
https://api.openweathermap.org/data/2.5/weather?q=London,ca&APPID=d582054f0f0dcf06c41ec1c6aa2bd8a9
I think that's what we are looking for, right?

**Comment by FOR-TIMI** [comment]
Nice!
